# Generated by Django 4.2.7 on 2025-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='current_price',
            field=models.CharField(help_text="Enter price (e.g., '1500', '₱3500/hectare', '1/9 sack')", max_length=100),
        ),
    ]
