# Generated by Django 4.2.7 on 2025-12-01 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0002_alter_machine_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online Payment'), ('face_to_face', 'Face-to-Face')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_slip',
            field=models.FileField(blank=True, null=True, upload_to='payment_slips/rentals/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
