# Generated by Django 4.2.7 on 2025-12-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_rental_payment_amount_rental_payment_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['machine', 'start_date', 'end_date', 'status'], name='rental_availability_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['start_date', 'end_date'], name='rental_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['user', 'status'], name='rental_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
    ]
