# Generated by Django 4.2.7 on 2026-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_add_rental_indexes_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='Stripe payment link for online payments', max_length=500, null=True),
        ),
    ]
