# Generated by Django 4.2.7 on 2026-02-20 14:55

from django.db import migrations, models
import machines.models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_machine_stripe_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payment_slip',
            field=models.FileField(blank=True, null=True, upload_to=machines.models.rental_payment_slip_path),
        ),
    ]
