# Generated by Django 4.2.7 on 2026-02-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_alter_rental_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Land area in hectares', max_digits=10, null=True),
        ),
    ]
