# Generated by Django 4.2.7 on 2026-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_rental_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='allow_face_to_face_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='allow_online_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='rental_price_type',
            field=models.CharField(choices=[('cash', 'Fixed Rate (Cash)'), ('in_kind', 'IN-KIND (Rice Share 9:1)')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='settlement_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('after_harvest', 'After Harvest')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='field_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='organization_share_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='organization_share_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('to_be_determined', 'TO BE DETERMINED'), ('pending', 'Pending'), ('paid', 'Paid'), ('paid_in_kind', 'PAID (IN-KIND)')], default='to_be_determined', max_length=30),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Fixed Rate (Cash)'), ('in_kind', 'IN-KIND (Rice Share 9:1)')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='settlement_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='settlement_status',
            field=models.CharField(choices=[('to_be_determined', 'TO BE DETERMINED'), ('waiting_for_delivery', 'WAITING FOR DELIVERY'), ('paid', 'PAID')], default='to_be_determined', max_length=30),
        ),
        migrations.AddField(
            model_name='rental',
            name='settlement_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('after_harvest', 'After Harvest')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_harvest_sacks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
