# Generated by Django 4.2.7 on 2026-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_machine_allow_face_to_face_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='in_kind_farmer_share',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='machine',
            name='in_kind_organization_share',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='machine',
            name='rental_price_type',
            field=models.CharField(choices=[('cash', 'Fixed Rate (Cash)'), ('in_kind', 'IN-KIND (Rice Share)')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Fixed Rate (Cash)'), ('in_kind', 'IN-KIND (Rice Share)')], default='cash', max_length=20),
        ),
    ]
