# Generated by Django 4.2.7 on 2026-03-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0014_add_operator_dashboard_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='harvestreport',
            new_name='machines_ha_rental__6891a0_idx',
            old_name='machines_ha_rental_idx',
        ),
        migrations.RenameIndex(
            model_name='harvestreport',
            new_name='machines_ha_recorde_cd38e0_idx',
            old_name='machines_ha_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='rentalstatechange',
            new_name='machines_re_rental__134a20_idx',
            old_name='machines_rs_rental_idx',
        ),
        migrations.RenameIndex(
            model_name='rentalstatechange',
            new_name='machines_re_changed_1a3f46_idx',
            old_name='machines_rs_changed_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='machines_se_rental__eb4f21_idx',
            old_name='machines_se_rental_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='machines_se_settlem_bd055c_idx',
            old_name='machines_se_reference_idx',
        ),
    ]
