# Generated by Django 4.2.7 on 2026-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_operator_operatortask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operator',
            new_name='machines_op_operato_6d07f1_idx',
            old_name='machines_op_operato_idx',
        ),
        migrations.RenameIndex(
            model_name='operator',
            new_name='machines_op_status_443d2f_idx',
            old_name='machines_op_status_idx',
        ),
        migrations.RenameIndex(
            model_name='operatortask',
            new_name='machines_op_operato_61e452_idx',
            old_name='machines_op_operato_status_idx',
        ),
        migrations.RenameIndex(
            model_name='operatortask',
            new_name='machines_op_schedul_eb1a40_idx',
            old_name='machines_op_schedul_idx',
        ),
        migrations.AlterField(
            model_name='rental',
            name='operator_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('traveling', 'Traveling'), ('operating', 'Operating'), ('completed', 'Work Completed'), ('harvest_complete', 'Harvest Complete'), ('harvest_reported', 'Harvest Reported')], default='unassigned', max_length=30),
        ),
    ]
