# Generated by Django 4.2.7 on 2026-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_rental_amount_paid_rental_or_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount received', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='or_number',
            field=models.CharField(blank=True, help_text='Official Receipt Number', max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Payment recording notes'),
        ),
    ]
