# Generated by Django 4.2.7 on 2026-03-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0022_recalculate_ricemill_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricemillappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Waiting for Payment'), ('paid', 'Paid - Waiting for Admin Confirmation'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DryerRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online Payment'), ('face_to_face', 'Face-to-Face Payment')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Waiting for Payment'), ('paid', 'Paid - Waiting for Admin Confirmation'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'flatbed_dryer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dryer_rentals', to='machines.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dryer_rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dryer Rental',
                'verbose_name_plural': 'Dryer Rentals',
                'ordering': ['-rental_date', '-created_at'],
            },
        ),
    ]
