# Generated by Django 4.2.7 on 2026-03-30 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0024_repair_rental_payment_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricemillappointment',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual milled rice weight in kilograms', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ricemillappointment',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ricemillappointment',
            name='sacks',
            field=models.PositiveIntegerField(default=1, help_text='Number of sacks requested for milling'),
        ),
    ]
