# Generated by Django 4.2.7 on 2026-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0026_dryerrental_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryerrental',
            name='hourly_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dryerrental',
            name='pricing_type_snapshot',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('until_dried', 'Until Dried')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='dryerrental',
            name='requested_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='dryer_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='dryer_pricing_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('until_dried', 'Until Dried')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='dryer_service_type',
            field=models.CharField(blank=True, choices=[('flatbed', 'Flatbed Dryer'), ('solar', 'Solar Dryer'), ('circulating', 'Circulating Dryer')], default='flatbed', max_length=20),
        ),
        migrations.AlterField(
            model_name='dryerrental',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dryerrental',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='rental_price_type',
            field=models.CharField(choices=[('cash', 'Fixed Rate (Cash)'), ('in_kind', 'Non-cash payment')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('to_be_determined', 'TO BE DETERMINED'), ('pending', 'Pending'), ('paid', 'Paid'), ('paid_in_kind', 'PAID (NON-CASH PAYMENT)')], default='to_be_determined', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Fixed Rate (Cash)'), ('in_kind', 'Non-cash payment')], default='cash', max_length=20),
        ),
    ]
