# Generated by Django 4.2.7 on 2026-04-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0027_dryerrental_hourly_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryerrental',
            name='machine',
            field=models.ForeignKey(limit_choices_to={'machine_type__in': ('flatbed_dryer', 'solar_dryer', 'circulating_dryer')}, on_delete=django.db.models.deletion.CASCADE, related_name='dryer_rentals', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('rice_mill', 'Rice Mill'), ('tractor_4wd', '4-Wheel Drive Tractor'), ('hand_tractor', 'Hand Tractor'), ('transplanter_walking', 'Walk-behind Transplanter'), ('transplanter_riding', 'Riding Type Transplanter'), ('precision_seeder', 'Precision Seeder'), ('harvester', 'Harvester'), ('flatbed_dryer', 'Flatbed Dryer'), ('solar_dryer', 'Solar Dryer'), ('circulating_dryer', 'Circulating Dryer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
