# Generated by Django 4.2.7 on 2026-04-07 09:56

from datetime import timedelta
from django.db import migrations, models


def backfill_dryer_rental_workflow(apps, schema_editor):
    DryerRental = apps.get_model('machines', 'DryerRental')

    status_map = {
        'paid': 'approved',
        'confirmed': 'approved',
        'ongoing': 'in_progress',
    }

    for rental in DryerRental.objects.all():
        legacy_pricing_type = getattr(rental, 'pricing_type_snapshot', None)
        rental.rental_type = legacy_pricing_type if legacy_pricing_type in {'hourly', 'until_dried'} else 'until_dried'

        if rental.rental_type == 'hourly':
            rental.estimated_end_date = rental.rental_date
        elif rental.estimated_end_date is None and getattr(rental, 'estimated_drying_days', None):
            rental.estimated_end_date = rental.rental_date + timedelta(days=max(rental.estimated_drying_days - 1, 0))

        rental.status = status_map.get(rental.status, rental.status)
        rental.save(update_fields=['rental_type', 'estimated_end_date', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0029_dryerrental_estimated_drying_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryerrental',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dryerrental',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dryerrental',
            name='goods_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dryerrental',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dryerrental',
            name='rental_type',
            field=models.CharField(choices=[('until_dried', 'Until Dried'), ('hourly', 'By Hour')], default='until_dried', max_length=20),
        ),
        migrations.AlterField(
            model_name='dryerrental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_confirmation', 'Waiting for Confirmation'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_dryer_rental_workflow, migrations.RunPython.noop),
    ]
