# Generated by Django 4.2.7 on 2026-04-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0030_dryerrental_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='no_parts_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='repair_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MaintenancePartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='machines.maintenance')),
            ],
            options={
                'verbose_name': 'Maintenance part used',
                'verbose_name_plural': 'Maintenance parts used',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
