# Generated by Django 4.2.7 on 2026-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0031_maintenance_completion_notes_maintenance_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryerrental',
            name='estimated_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dryerrental',
            name='pricing_type_snapshot',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('per_sack', 'Per Sack'), ('until_dried', 'Until Dried')], default='hourly', max_length=20),
        ),
        migrations.AlterField(
            model_name='dryerrental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_confirmation', 'Waiting for Confirmation'), ('approved', 'Approved'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='dryer_pricing_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('per_sack', 'Per Sack'), ('until_dried', 'Until Dried')], default='hourly', max_length=20),
        ),
    ]
