# Generated by Django 4.2.7 on 2026-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_ricemillappointment_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='actual_pickup_at',
            field=models.DateTimeField(blank=True, help_text='Actual time when the machine was picked up or handed over.', null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='actual_return_at',
            field=models.DateTimeField(blank=True, help_text='Actual time when the machine was returned.', null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='scheduled_pickup_at',
            field=models.DateTimeField(blank=True, help_text='Planned pickup or handover time for admin overdue tracking.', null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='scheduled_return_at',
            field=models.DateTimeField(blank=True, help_text='Planned return time for admin overdue tracking.', null=True),
        ),
        migrations.AlterField(
            model_name='dryerrental',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Gcash Payment'), ('face_to_face', 'Over the Counter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Gcash Payment'), ('face_to_face', 'Over the Counter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ricemillappointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Gcash Payment'), ('face_to_face', 'Over the Counter')], max_length=20, null=True),
        ),
    ]
