# Generated by Django 4.2.7 on 2026-04-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0040_rental_cancellation_follow_up_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricemillappointment',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
