# Generated by Django 4.2.7 on 2026-04-26 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0041_increase_time_slot_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='Whole Farming Service Package', max_length=150)),
                ('farmer_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('preferred_start_date', models.DateField()),
                ('preferred_timeline_notes', models.CharField(blank=True, max_length=255)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('partially_scheduled', 'Partially Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('not_required', 'Not Required Yet')], default='pending', max_length=20)),
                ('payment_preference', models.CharField(blank=True, choices=[('', 'To Be Determined'), ('online', 'Gcash Payment'), ('face_to_face', 'Over the Counter')], default='', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rental_packages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Package',
                'verbose_name_plural': 'Rental Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('rice_mill', 'Rice Mill'), ('tractor_4wd', '4-Wheel Drive Tractor'), ('hand_tractor', 'Hand Tractor'), ('transplanter_walking', 'Walk-behind Transplanter'), ('transplanter_riding', 'Riding Type Transplanter'), ('precision_seeder', 'Precision Seeder'), ('harvester', 'Harvester'), ('thresher', 'Thresher'), ('flatbed_dryer', 'Flatbed Dryer'), ('solar_dryer', 'Solar Dryer'), ('circulating_dryer', 'Circulating Dryer'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='Legacy online payment link field retained for compatibility.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='workflow_state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('conflict_review', 'Conflict Review'), ('harvest_report_submitted', 'Harvest Report Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
        migrations.CreateModel(
            name='RentalPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('tractor', 'Tractor / Plowing'), ('rotavator', 'Rotavator / Land Cultivation'), ('planter', 'Planter'), ('harvester', 'Harvester'), ('thresher', 'Thresher')], max_length=20)),
                ('service_name', models.CharField(max_length=150)),
                ('machine_type_required', models.CharField(max_length=20)),
                ('pricing_unit', models.CharField(blank=True, choices=[('day', 'Per Day'), ('hectare', 'Per Hectare'), ('flat', 'Flat Fee'), ('sack', 'Per Sack'), ('hour', 'Per Hour'), ('kg', 'Per Kilogram')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('suggested_start', models.DateField(blank=True, null=True)),
                ('suggested_end', models.DateField(blank=True, null=True)),
                ('scheduled_start', models.DateField(blank=True, null=True)),
                ('scheduled_end', models.DateField(blank=True, null=True)),
                ('is_tentative', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('tentative', 'Tentative'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('not_included', 'Not Included')], default='requested', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_rental', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_item', to='machines.rental')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_items', to='machines.machine')),
                ('rental_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='machines.rentalpackage')),
            ],
            options={
                'verbose_name': 'Rental Package Item',
                'verbose_name_plural': 'Rental Package Items',
                'ordering': ['sequence_order', 'created_at', 'pk'],
            },
        ),
    ]
