# Generated by Django 4.2.7 on 2026-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0044_machine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('to_be_determined', 'TO BE DETERMINED'), ('pending', 'Pending'), ('partially_settled', 'Partially Settled'), ('paid', 'Paid'), ('paid_in_kind', 'PAID (NON-CASH PAYMENT)')], default='to_be_determined', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='settlement_status',
            field=models.CharField(choices=[('to_be_determined', 'TO BE DETERMINED'), ('pending', 'Pending'), ('waiting_for_delivery', 'WAITING FOR DELIVERY'), ('partially_settled', 'PARTIALLY SETTLED'), ('paid', 'PAID'), ('cancelled', 'Cancelled')], default='to_be_determined', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='workflow_state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('ready_for_payment', 'Ready for Payment'), ('ready_for_operation', 'Ready for Operation'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('conflict_review', 'Conflict Review'), ('harvest_report_submitted', 'Harvest Report Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
    ]
