# Generated by Django 4.2.7 on 2026-04-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0045_alter_rental_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='diesel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diesel consumed in liters during operation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='diesel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of diesel consumed', max_digits=10, null=True),
        ),
    ]
