# Generated by Django 4.2.7 on 2026-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0051_remove_machineimage_cloudinary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricemillappointment',
            name='booking_source',
            field=models.CharField(choices=[('member', 'Member Milling'), ('non_member', 'Non-member Milling'), ('bufia_rice_share', 'BUFIA Rice Share')], default='member', max_length=30),
        ),
    ]
