# Generated by Django 5.2.1 on 2025-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has an approved membership form'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_approved_date',
            field=models.DateField(blank=True, help_text='Date when membership was approved', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_form_date',
            field=models.DateField(blank=True, help_text='Date when membership form was submitted', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_form_submitted',
            field=models.BooleanField(default=False, help_text='Indicates if user has submitted membership form'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_rejected_reason',
            field=models.TextField(blank=True, help_text='Reason for membership rejection if applicable'),
        ),
    ]
