# Generated by Django 5.2.1 on 2025-06-01 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True, help_text="Indicates if this is the user's current application")),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=50)),
                ('sitio', models.CharField(blank=True, max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('ownership_type', models.CharField(max_length=50)),
                ('land_owner', models.CharField(blank=True, max_length=200)),
                ('farm_manager', models.CharField(blank=True, max_length=200)),
                ('farm_location', models.CharField(max_length=200)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-submission_date'],
            },
        ),
    ]
