# Generated by Django 5.2.1 on 2025-06-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_membershipapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipapplication',
            options={'verbose_name': 'Membership Application', 'verbose_name_plural': 'Membership Applications'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether this user's membership has been verified"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership_form_submitted',
            field=models.BooleanField(default=False, help_text='Whether the user has submitted membership form'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='education',
            field=models.CharField(blank=True, choices=[('elementary', 'Elementary'), ('high_school', 'High School'), ('vocational', 'Vocational'), ('college', 'College'), ('graduate', 'Graduate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='farm_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='farm_manager',
            field=models.CharField(blank=True, help_text='Name of farm manager if not self', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in hectares', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Whether this is the current application'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='land_owner',
            field=models.CharField(blank=True, help_text='Name of land owner if not owned', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('leased', 'Leased'), ('tenant', 'Tenant'), ('shared', 'Shared')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='sitio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
