# Generated by Django 5.2.1 on 2025-06-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_membershipapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='is_tiller',
            field=models.BooleanField(default=False, help_text='Whether the member is an actual tiller'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Lot number of the farm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.sector'),
        ),
    ]
