# Generated by Django 5.2.1 on 2025-06-01 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sector_membershipapplication_is_tiller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
