# Generated by Django 5.2.1 on 2025-06-02 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_membershipapplication_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='assigned_sector',
            field=models.ForeignKey(blank=True, help_text='Sector assigned by admin during verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='users.sector'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='bufia_farm_location',
            field=models.CharField(blank=True, help_text="Specific location of the farm within BUFIA's jurisdiction", max_length=200, null=True),
        ),
    ]
