# Generated by Django 5.2.1 on 2025-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_membershipapplication_assigned_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_sectors',
            field=models.ManyToManyField(blank=True, help_text='Sectors managed by this water tender', related_name='water_tenders', to='users.sector'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('superuser', 'Superuser'), ('regular_user', 'Regular User'), ('water_tender', 'Water Tender')], default='regular_user', max_length=20),
        ),
    ]
