# Generated by Django 5.2.1 on 2025-06-03 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_managed_sectors_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('approve', 'Approve'), ('reject', 'Reject'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where activity originated from', null=True)),
                ('content_type', models.CharField(blank=True, help_text="Type of object that was affected (e.g., 'User', 'MembershipApplication')", max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object that was affected', max_length=100)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=200)),
                ('additional_data', models.JSONField(blank=True, help_text='Additional JSON data related to the activity', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
