# Generated by Django 5.2.1 on 2025-06-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
