# Generated by Django 5.2.1 on 2025-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid', max_digits=8),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_completed',
            field=models.BooleanField(default=False, help_text='Whether payment has been completed'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When the payment was completed', null=True),
        ),
    ]
