# Generated by Django 5.2.1 on 2025-06-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_membershipapplication_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='payment_completed',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='paymongo_id',
            field=models.CharField(blank=True, help_text='PayMongo payment ID', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='paymongo_payment_intent_id',
            field=models.CharField(blank=True, help_text='PayMongo payment intent ID', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='paymongo_source_id',
            field=models.CharField(blank=True, help_text='PayMongo source ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Membership fee amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
