# Generated by Django 5.2.1 on 2025-06-03 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_membershipapplication_payment_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='paymongo_id',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='paymongo_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='paymongo_source_id',
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_data', models.JSONField(blank=True, help_text='Additional payment data/metadata', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Payment',
                'verbose_name_plural': 'Membership Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
