# Generated by Django 5.2.1 on 2025-06-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_membershipapplication_payment_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPayment',
        ),
    ]
