# Generated by Django 5.2.1 on 2025-06-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_membershippayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='payment_status',
        ),
    ]
