# Generated by Django 5.2.1 on 2025-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_membershipapplication_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('regular_user', 'Regular User'), ('water_tender', 'Water Tender')], default='regular_user', max_length=20),
        ),
    ]
