# Generated by Django 4.2.7 on 2025-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('face_to_face', 'Face-to-Face Payment')], default='face_to_face', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
    ]
