# Generated by Django 4.2.7 on 2026-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('regular_user', 'Regular User'), ('water_tender', 'Water Tender'), ('operator', 'Operator')], default='regular_user', max_length=20),
        ),
    ]
