# Generated by Django 4.2.7 on 2026-03-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_make_sector_number_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershipapplication',
            new_name='users_membe_sector__fde3ad_idx',
            old_name='users_membe_sector__idx',
        ),
        migrations.RenameIndex(
            model_name='membershipapplication',
            new_name='users_membe_assigne_cbc214_idx',
            old_name='users_membe_assigne_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipapplication',
            new_name='users_membe_payment_2d3e01_idx',
            old_name='users_membe_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipapplication',
            new_name='users_membe_submiss_6aa13e_idx',
            old_name='users_membe_submiss_idx',
        ),
        migrations.RenameIndex(
            model_name='sector',
            new_name='users_secto_sector__cca8fe_idx',
            old_name='users_secto_sector__idx',
        ),
        migrations.RenameIndex(
            model_name='sector',
            new_name='users_secto_is_acti_0ceac3_idx',
            old_name='users_secto_is_acti_idx',
        ),
    ]
