# Generated by Django 4.2.7 on 2026-04-12 15:44

import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _as_datetime(value):
    if not value:
        return None
    if isinstance(value, datetime.datetime):
        if django.utils.timezone.is_aware(value):
            return value
        return django.utils.timezone.make_aware(value, django.utils.timezone.get_current_timezone())
    combined = datetime.datetime.combine(value, datetime.time.min)
    return django.utils.timezone.make_aware(combined, django.utils.timezone.get_current_timezone())


def _display_name(user):
    full_name = f"{(getattr(user, 'first_name', '') or '').strip()} {(getattr(user, 'last_name', '') or '').strip()}".strip()
    return full_name or getattr(user, 'username', '') or 'User'


def _create_log(ActivityLog, **kwargs):
    lookup = {
        'activity_type': kwargs['activity_type'],
        'related_model': kwargs.get('related_model', ''),
        'related_object_id': kwargs.get('related_object_id', ''),
        'title': kwargs['title'],
    }
    if ActivityLog.objects.filter(**lookup).exists():
        return
    ActivityLog.objects.create(**kwargs)


def backfill_activity_logs(apps, schema_editor):
    ActivityLog = apps.get_model('users', 'ActivityLog')
    CustomUser = apps.get_model('users', 'CustomUser')
    MembershipApplication = apps.get_model('users', 'MembershipApplication')
    Rental = apps.get_model('machines', 'Rental')
    RiceMillAppointment = apps.get_model('machines', 'RiceMillAppointment')
    DryerRental = apps.get_model('machines', 'DryerRental')
    IrrigationSeasonRecord = apps.get_model('irrigation', 'IrrigationSeasonRecord')

    for user in CustomUser.objects.all():
        _create_log(
            ActivityLog,
            actor_id=user.pk,
            subject_user_id=user.pk,
            activity_type='register',
            visibility='both',
            title=f'{_display_name(user)} created a BUFIA account',
            description='Account registration was completed successfully.',
            related_model='users.CustomUser',
            related_object_id=str(user.pk),
            created_at=_as_datetime(user.date_joined),
        )

    for application in MembershipApplication.objects.select_related('user', 'assigned_sector', 'reviewed_by'):
        user = application.user
        user_name = _display_name(user)

        _create_log(
            ActivityLog,
            actor_id=user.pk,
            subject_user_id=user.pk,
            activity_type='submit',
            visibility='both',
            title=f'{user_name} submitted a membership application',
            description='Membership application was submitted for review.',
            related_model='users.MembershipApplication',
            related_object_id=str(application.pk),
            created_at=_as_datetime(application.submission_date),
        )

        if application.payment_status == 'paid' and application.payment_date:
            _create_log(
                ActivityLog,
                actor_id=user.pk,
                subject_user_id=user.pk,
                activity_type='payment',
                visibility='both',
                title=f'{user_name} completed the membership payment',
                description='Membership payment was received and is waiting for admin review.',
                related_model='users.MembershipApplication',
                related_object_id=str(application.pk),
                created_at=_as_datetime(application.payment_date),
            )

        if application.is_approved and application.review_date:
            _create_log(
                ActivityLog,
                actor_id=getattr(application, 'reviewed_by_id', None),
                subject_user_id=user.pk,
                activity_type='approve',
                visibility='both',
                title=f'Membership approved for {user_name}',
                description=f'Assigned sector: {application.assigned_sector.name if application.assigned_sector else "Not assigned"}.',
                related_model='users.MembershipApplication',
                related_object_id=str(application.pk),
                created_at=_as_datetime(application.review_date),
            )
        elif application.is_rejected and application.review_date:
            _create_log(
                ActivityLog,
                actor_id=getattr(application, 'reviewed_by_id', None),
                subject_user_id=user.pk,
                activity_type='reject',
                visibility='both',
                title=f'Membership rejected for {user_name}',
                description=f'Reason: {application.rejection_reason or "No reason recorded."}',
                related_model='users.MembershipApplication',
                related_object_id=str(application.pk),
                created_at=_as_datetime(application.review_date),
            )

    for rental in Rental.objects.select_related('user', 'machine'):
        user_name = _display_name(rental.user)
        _create_log(
            ActivityLog,
            actor_id=rental.user_id,
            subject_user_id=rental.user_id,
            activity_type='submit',
            visibility='both',
            title=f'{user_name} submitted a machine rental request',
            description=f'{rental.machine.name} from {rental.start_date:%b %d, %Y} to {rental.end_date:%b %d, %Y}.',
            related_model='machines.Rental',
            related_object_id=str(rental.pk),
            created_at=_as_datetime(rental.created_at),
        )

        if rental.status == 'approved':
            _create_log(
                ActivityLog,
                subject_user_id=rental.user_id,
                activity_type='approve',
                visibility='both',
                title=f'{rental.machine.name} rental was approved for {user_name}',
                description=f'Schedule: {rental.start_date:%b %d, %Y} to {rental.end_date:%b %d, %Y}.',
                related_model='machines.Rental',
                related_object_id=str(rental.pk),
                created_at=_as_datetime(rental.updated_at),
            )
        elif rental.status == 'rejected':
            _create_log(
                ActivityLog,
                subject_user_id=rental.user_id,
                activity_type='reject',
                visibility='both',
                title=f'{rental.machine.name} rental was rejected for {user_name}',
                description=f'Requested schedule was {rental.start_date:%b %d, %Y} to {rental.end_date:%b %d, %Y}.',
                related_model='machines.Rental',
                related_object_id=str(rental.pk),
                created_at=_as_datetime(rental.updated_at),
            )

    for appointment in RiceMillAppointment.objects.select_related('user', 'machine'):
        user_name = _display_name(appointment.user)
        _create_log(
            ActivityLog,
            actor_id=appointment.user_id,
            subject_user_id=appointment.user_id,
            activity_type='submit',
            visibility='both',
            title=f'{user_name} submitted a rice mill appointment',
            description=f'{appointment.machine.name} on {appointment.appointment_date:%b %d, %Y}.',
            related_model='machines.RiceMillAppointment',
            related_object_id=str(appointment.pk),
            created_at=_as_datetime(appointment.created_at),
        )

        if appointment.status == 'approved':
            _create_log(
                ActivityLog,
                subject_user_id=appointment.user_id,
                activity_type='approve',
                visibility='both',
                title=f'Rice mill appointment approved for {user_name}',
                description=f'{appointment.machine.name} on {appointment.appointment_date:%b %d, %Y}.',
                related_model='machines.RiceMillAppointment',
                related_object_id=str(appointment.pk),
                created_at=_as_datetime(appointment.updated_at),
            )
        elif appointment.status in ['paid', 'confirmed']:
            _create_log(
                ActivityLog,
                subject_user_id=appointment.user_id,
                activity_type='payment',
                visibility='both',
                title=f'Rice mill payment recorded for {user_name}',
                description=f'Total amount: PHP {appointment.total_amount}.',
                related_model='machines.RiceMillAppointment',
                related_object_id=str(appointment.pk),
                created_at=_as_datetime(appointment.updated_at),
            )

    for dryer_rental in DryerRental.objects.select_related('user', 'machine'):
        user_name = _display_name(dryer_rental.user)
        _create_log(
            ActivityLog,
            actor_id=dryer_rental.user_id,
            subject_user_id=dryer_rental.user_id,
            activity_type='submit',
            visibility='both',
            title=f'{user_name} submitted a dryer request',
            description=f'{dryer_rental.machine.name} on {dryer_rental.rental_date:%b %d, %Y}.',
            related_model='machines.DryerRental',
            related_object_id=str(dryer_rental.pk),
            created_at=_as_datetime(dryer_rental.created_at),
        )

        if dryer_rental.status in ['approved', 'in_progress']:
            _create_log(
                ActivityLog,
                subject_user_id=dryer_rental.user_id,
                activity_type='approve',
                visibility='both',
                title=f'Dryer request approved for {user_name}',
                description=f'{dryer_rental.machine.name} on {dryer_rental.rental_date:%b %d, %Y}.',
                related_model='machines.DryerRental',
                related_object_id=str(dryer_rental.pk),
                created_at=_as_datetime(dryer_rental.updated_at),
            )
        elif dryer_rental.status == 'paid':
            _create_log(
                ActivityLog,
                subject_user_id=dryer_rental.user_id,
                activity_type='payment',
                visibility='both',
                title=f'Dryer payment recorded for {user_name}',
                description=f'Amount due: PHP {dryer_rental.total_amount}.',
                related_model='machines.DryerRental',
                related_object_id=str(dryer_rental.pk),
                created_at=_as_datetime(dryer_rental.updated_at),
            )
        elif dryer_rental.status == 'rejected':
            _create_log(
                ActivityLog,
                subject_user_id=dryer_rental.user_id,
                activity_type='reject',
                visibility='both',
                title=f'Dryer request rejected for {user_name}',
                description=f'{dryer_rental.machine.name} on {dryer_rental.rental_date:%b %d, %Y}.',
                related_model='machines.DryerRental',
                related_object_id=str(dryer_rental.pk),
                created_at=_as_datetime(dryer_rental.updated_at),
            )

    for record in IrrigationSeasonRecord.objects.select_related('farmer', 'season', 'payment_confirmed_by'):
        farmer_name = _display_name(record.farmer)
        if record.billed_at and (record.total_fee or 0) > 0:
            _create_log(
                ActivityLog,
                subject_user_id=record.farmer_id,
                activity_type='billing',
                visibility='both',
                title=f'Irrigation billing generated for {farmer_name}',
                description=f'{record.season.name}: PHP {record.total_fee} billed for {record.farm_area} ha.',
                related_model='irrigation.IrrigationSeasonRecord',
                related_object_id=str(record.pk),
                created_at=_as_datetime(record.billed_at),
            )

        if record.paid_at and (record.amount_paid or 0) > 0:
            _create_log(
                ActivityLog,
                actor_id=getattr(record, 'payment_confirmed_by_id', None),
                subject_user_id=record.farmer_id,
                activity_type='payment',
                visibility='both',
                title=f'Irrigation payment recorded for {farmer_name}',
                description=f'{record.season.name}: PHP {record.amount_paid} settled.',
                related_model='irrigation.IrrigationSeasonRecord',
                related_object_id=str(record.pk),
                created_at=_as_datetime(record.paid_at),
            )


def clear_backfilled_activity_logs(apps, schema_editor):
    ActivityLog = apps.get_model('users', 'ActivityLog')
    ActivityLog.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customuser_must_change_password'),
        ('machines', '0034_dryerrental_actual_drying_hours'),
        ('irrigation', '0008_irrigationseasonrecord_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('register', 'Register'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('payment', 'Payment'), ('schedule', 'Schedule'), ('machine', 'Machine'), ('billing', 'Billing'), ('update', 'Update'), ('other', 'Other')], default='other', max_length=20)),
                ('visibility', models.CharField(choices=[('admin', 'Admin Only'), ('user', 'User Only'), ('both', 'Admin and User')], default='both', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_actions', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_feed_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='users_activ_created_31380b_idx'), models.Index(fields=['activity_type', 'created_at'], name='users_activ_activit_122dfc_idx'), models.Index(fields=['visibility', 'created_at'], name='users_activ_visibil_2420bc_idx'), models.Index(fields=['subject_user', 'created_at'], name='users_activ_subject_098e3e_idx'), models.Index(fields=['actor', 'created_at'], name='users_activ_actor_i_76a8d4_idx'), models.Index(fields=['related_model', 'related_object_id'], name='users_activ_related_5b7113_idx')],
            },
        ),
        migrations.RunPython(backfill_activity_logs, clear_backfilled_activity_logs),
    ]
