# Generated by Django 4.2.7 on 2026-04-13 07:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='land_proof_document',
            field=models.FileField(blank=True, help_text='Clear photo or file showing land ownership or tenancy proof.', null=True, upload_to='membership/land_proofs/', validators=[users.models.validate_membership_land_proof]),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='land_proof_notes',
            field=models.TextField(blank=True, help_text='Optional notes from the applicant about the uploaded land proof.'),
        ),
    ]
