# Generated by Django 4.2.7 on 2026-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_membershipapplication_land_proof_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Remind the user to change their password (not enforced).'),
        ),
    ]
