# Generated by Django 4.2.7 on 2026-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_membershipapplicationproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Gcash Payment'), ('face_to_face', 'Over the Counter')], default='face_to_face', max_length=20),
        ),
    ]
