# Generated by Django 4.2.7 on 2026-04-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_membershipapplication_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National ID number provided by the applicant.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='rcba_number',
            field=models.CharField(blank=True, help_text='BUFIA-issued RCBA number assigned by admin.', max_length=50, null=True),
        ),
    ]
