# Generated by Django 4.2.7 on 2026-04-23 07:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_membershipapplication_national_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='valid_id_document',
            field=models.FileField(blank=True, help_text='Clear photo or scanned copy of a valid ID.', null=True, upload_to='membership/valid_ids/', validators=[users.models.validate_membership_land_proof]),
        ),
    ]
