# Generated by Django 4.2.7 on 2026-04-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_membershipapplication_valid_id_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='finalized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='survey_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='survey_ready_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='surveyed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveyed_membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='surveyed_farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('ready_for_survey', 'Ready for Survey'), ('surveyed', 'Survey Completed'), ('finalized', 'Final Approved'), ('rejected', 'Rejected')], default='submitted', help_text='Current membership workflow stage.', max_length=30),
        ),
    ]
