# Generated by Django 4.2.7 on 2026-04-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_membershipapplication_finalized_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin visible to the member after membership is approved.'),
        ),
    ]
