# Generated by Django 4.2.7 on 2026-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_add_admin_notes_to_membership_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_approval_banner_seen',
            field=models.BooleanField(default=False, help_text='Whether the user has dismissed the membership approval congratulations banner.'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='rcba_number',
            field=models.CharField(blank=True, help_text='BUFIA-issued RSBSA number assigned by admin.', max_length=50, null=True),
        ),
    ]
