services:
  - type: web
    name: bufia
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "bash build.sh"
    preDeployCommand: "bash predeploy.sh"
    startCommand: "gunicorn bufia.wsgi:application"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: bufia-db
          property: connectionString
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: PAYMONGO_PUBLIC_KEY
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_WEBHOOK_SECRET
        sync: false
      - key: PAYMONGO_PAYMENT_METHODS
        value: gcash
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: bufia-db
    databaseName: bufia
    user: bufia
    region: singapore
    plan: free
