# Generated by Django 4.2.7 on 2026-02-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_transaction_id', models.CharField(blank=True, db_index=True, editable=False, help_text='Internal transaction ID (BUF-TXN-YYYY-NNNNN)', max_length=50, null=True, unique=True)),
                ('payment_type', models.CharField(choices=[('rental', 'Machine Rental'), ('appointment', 'Rice Mill Appointment'), ('irrigation', 'Irrigation Request')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['internal_transaction_id'], name='bufia_payme_interna_c8c238_idx'), models.Index(fields=['user', 'status'], name='bufia_payme_user_id_8b550a_idx'), models.Index(fields=['created_at'], name='bufia_payme_created_e91e7e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_transaction_id__isnull', False)), fields=('internal_transaction_id',), name='unique_internal_transaction_id'),
        ),
    ]
