# Generated by Django 4.2.7 on 2026-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bufia', '0001_add_internal_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Charge ID', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='bufia_payme_stripe__1622a2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_charge_id'], name='bufia_payme_stripe__095c40_idx'),
        ),
    ]
