# Generated by Django 4.2.7 on 2026-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bufia', '0002_payment_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rental', 'Machine Rental'), ('appointment', 'Rice Mill Appointment'), ('dryer', 'Dryer Rental'), ('irrigation', 'Irrigation Request'), ('membership', 'Membership Fee')], max_length=20),
        ),
    ]
