# Generated by Django 4.2.7 on 2026-04-20 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bufia', '0005_payment_over_counter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual / Office Adjustment')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='refunded', max_length=20)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bufia.payment')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bufia_refun_status_17460d_idx'), models.Index(fields=['refunded_at'], name='bufia_refun_refunde_f4458a_idx'), models.Index(fields=['created_at'], name='bufia_refun_created_55b8ce_idx')],
            },
        ),
    ]
