# Generated by Django 4.2.7 on 2026-04-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bufia', '0006_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rental', 'Machine Rental'), ('appointment', 'Rice Mill Appointment'), ('rice_sale', 'Rice Sale'), ('dryer', 'Dryer Rental'), ('irrigation', 'Irrigation Request'), ('membership', 'Membership Fee')], max_length=20),
        ),
    ]
