# Generated by Django 5.2.1 on 2025-06-03 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_remove_membershipapplication_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIrrigationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField(help_text='Requested date for irrigation')),
                ('duration_hours', models.PositiveIntegerField(help_text='Requested duration in hours')),
                ('purpose', models.CharField(help_text='Purpose of irrigation', max_length=255)),
                ('crop_type', models.CharField(help_text='Type of crop being irrigated', max_length=100)),
                ('area_size', models.DecimalField(decimal_places=2, help_text='Size of area to be irrigated (hectares)', max_digits=8)),
                ('farm_location', models.CharField(blank=True, help_text='Farm location description', max_length=255, null=True)),
                ('bufia_farm_location', models.CharField(blank=True, help_text="Specific location within BUFIA's jurisdiction", max_length=255, null=True)),
                ('canal_number', models.CharField(blank=True, help_text='Canal number for irrigation', max_length=50)),
                ('block_number', models.CharField(blank=True, help_text='Block number of the farm', max_length=50)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements for irrigation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('status_notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_requests', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_requests', to='users.membershipapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_irrigation_requests', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_requests', to='users.sector')),
            ],
            options={
                'verbose_name': 'Water Irrigation Request',
                'verbose_name_plural': 'Water Irrigation Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='irrigation.waterirrigationrequest')),
            ],
            options={
                'verbose_name': 'Irrigation Request History',
                'verbose_name_plural': 'Irrigation Request Histories',
                'ordering': ['-changed_date'],
            },
        ),
    ]
