# Generated by Django 5.2.1 on 2025-06-03 23:25

import django.db.models.deletion
from django.db import migrations, models


def update_null_sectors(apps, schema_editor):
    """Updates any NULL sector values to a default sector before making the field NOT NULL"""
    WaterIrrigationRequest = apps.get_model('irrigation', 'WaterIrrigationRequest')
    Sector = apps.get_model('users', 'Sector')
    
    # Handle case where there are no sectors at all
    default_sector = None
    if Sector.objects.exists():
        default_sector = Sector.objects.first()
    else:
        default_sector = Sector.objects.create(name="Default Sector", description="Default sector created for data migration")
    
    # Update all rows with NULL sectors
    WaterIrrigationRequest.objects.filter(sector__isnull=True).update(sector=default_sector)


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
        ('users', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(update_null_sectors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='waterirrigationrequest',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irrigation_requests', to='users.sector'),
        ),
    ]
