# Generated by Django 5.2.1 on 2025-06-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_alter_waterirrigationrequest_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterirrigationrequest',
            name='title',
            field=models.CharField(blank=True, help_text="A brief title for this irrigation request (e.g., 'Weekly Watering Field A')", max_length=150, null=True),
        ),
    ]
