# Generated by Django 5.2.1 on 2025-06-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_waterirrigationrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterirrigationrequest',
            name='title',
        ),
    ]
