# Generated by Django 4.2.7 on 2026-03-19 17:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_rename_users_membe_sector__idx_users_membe_sector__fde3ad_idx_and_more'),
        ('irrigation', '0004_remove_waterirrigationrequest_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('irrigation_rate_per_hectare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('harvested', 'Harvested'), ('paid', 'Paid'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('billing_generated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_irrigation_seasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationSeasonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('irrigation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('harvested', 'Harvested'), ('paid', 'Paid'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_season_records', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_season_records', to='users.membershipapplication')),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_irrigation_payments', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='irrigation.croppingseason')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_season_records', to='users.sector')),
            ],
            options={
                'ordering': ['farmer__last_name', 'farmer__first_name'],
                'unique_together': {('season', 'farmer')},
            },
        ),
    ]
