# Generated by Django 4.2.7 on 2026-04-12 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0006_repair_irrigation_season_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppingseason',
            name='irrigation_rate_per_hectare',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10),
        ),
    ]
