# Generated by Django 4.2.7 on 2026-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0007_alter_croppingseason_irrigation_rate_per_hectare'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationseasonrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online Payment'), ('face_to_face', 'Face-to-Face Payment')], default='', max_length=20),
        ),
    ]
