# Generated by Django 4.2.7 on 2026-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0008_irrigationseasonrecord_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationseasonrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Gcash Payment'), ('face_to_face', 'Over the Counter')], default='', max_length=20),
        ),
    ]
