"""
Django settings for bufia project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def _get_env_bool(name, default=False):
    value = str(config(name, default=default)).strip().lower()
    truthy = {'1', 'true', 't', 'yes', 'y', 'on', 'debug', 'development', 'dev'}
    falsy = {'0', 'false', 'f', 'no', 'n', 'off', '', 'release', 'prod', 'production'}

    if value in truthy:
        return True
    if value in falsy:
        return False
    return bool(default)


def _split_csv(value):
    return [item.strip() for item in value.split(',') if item.strip()]


RAW_SECRET_KEY = config('SECRET_KEY', default='').strip()
DATABASE_URL = config('DATABASE_URL', default='').strip()
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='').strip()
HAS_DEPLOYMENT_ENV = any([RAW_SECRET_KEY, DATABASE_URL, RENDER_EXTERNAL_HOSTNAME])

# Default to local-friendly development mode when deployment env vars are absent.
DEBUG = _get_env_bool(
    'DEBUG',
    default=not HAS_DEPLOYMENT_ENV,
)
if not HAS_DEPLOYMENT_ENV and not RAW_SECRET_KEY:
    DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = RAW_SECRET_KEY
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'unsafe-local-dev-secret-key'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.trycloudflare.com',
    'testserver',
    '.onrender.com',
]
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
ALLOWED_HOSTS.extend(_split_csv(config('ALLOWED_HOSTS', default='')))
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# Allow CSRF for local development, temporary tunnels, and the live Render host.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.trycloudflare.com',
    'https://*.onrender.com',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
CSRF_TRUSTED_ORIGINS.extend(_split_csv(config('CSRF_TRUSTED_ORIGINS', default='')))
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # Local apps
    'bufia',  # Project app for Payment model
    'users.apps.UsersConfig',
    'machines.apps.MachinesConfig',
    'notifications.apps.NotificationsConfig',
    'reports.apps.ReportsConfig',
    'irrigation.apps.IrrigationConfig',
    'general_reports.apps.GeneralReportsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bufia.middleware.AccessControlMiddleware',  # Custom access control middleware
    'users.middleware.VerificationCheckMiddleware',  # Verification middleware
    'bufia.middleware.NoCacheForAuthenticatedMiddleware',  # Prevent caching of authenticated pages
    'bufia.middleware.LogoutCacheControlMiddleware',  # Cache control for logout
]

ROOT_URLCONF = 'bufia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'bufia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

# Use DATABASE_URL if set (Render/production), otherwise fall back to SQLite
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
render_disk_path = config('RENDER_DISK_PATH', default='').strip()
default_media_root = os.path.join(render_disk_path, 'media') if render_disk_path else os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = config('MEDIA_ROOT', default=default_media_root)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Authentication settings
AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'account_login'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Django AllAuth settings
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SIGNUP_FORM_CLASS = 'users.forms.TermsSignupForm'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect to custom dashboard after login
LOGOUT_REDIRECT_URL = '/'

# Stripe Configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Payment amounts (in cents for Stripe)
RENTAL_PAYMENT_AMOUNT = 5000  # $50.00 - adjust as needed
IRRIGATION_PAYMENT_AMOUNT = 3000  # $30.00 - adjust as needed

# Security Settings
SECURE_SSL_REDIRECT = _get_env_bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = _get_env_bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = _get_env_bool('CSRF_COOKIE_SECURE', default=False)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'DENY'

# Rate limiting
RATELIMIT_ENABLE = _get_env_bool('RATELIMIT_ENABLE', default=True)

# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    }
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'bufia': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

