# Generated by Django 4.2.7 on 2025-12-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Direct URL to navigate to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_object_id',
            field=models.IntegerField(blank=True, help_text='ID of the related object (rental, appointment, etc.)', null=True),
        ),
    ]
